language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
sudo: required
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch || true
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --batch || true
deploy:
  -
    provider: script
    script: mvn clean deploy --settings .travis/settings.xml -DskipTests=true -B -U
    skip_cleanup: true
    on:
      repo: $TRAVIS_REPO_SLUG
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: mvn --settings .travis/settings.xml org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=$TRAVIS_TAG 1>/dev/null 2>/dev/null; mvn clean deploy --settings .travis/settings.xml -DskipTests=true -B -U
    skip_cleanup: true
    on:
      repo: $TRAVIS_REPO_SLUG
      tags: true
      jdk: oraclejdk8
  